Switched to third party plugin
Currently trying to deal with the following dependency problem:

09:21:54.256 [main] DEBUG org.jooq.tools.Convert - Jackson is available
09:21:54.296 [main] DEBUG org.jooq.tools.Convert - JAXB not available       : jakarta/activation/DataSource
Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/persistence/PersistenceException